=== samiksha61/php/tu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Define the TU element as the root -->
  <xs:element name="TU">
    <xs:complexType>
      <xs:sequence>
        <!-- Define the employee element -->
        <xs:element name="employee" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <!-- Define the elements for employee -->
              <xs:element name="post">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minInclusive value="5"/>
                    <xs:maxInclusive value="8"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="salary">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="25000"/>
                    <xs:maxInclusive value="50000"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="gender">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="male"/>
                    <xs:enumeration value="female"/>
                    <xs:enumeration value="other"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="username">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minInclusive value="8"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="password">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Za-z].{7,}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== samiksha61/php/tu.xml
<?xml version="1.0" encoding="UTF-8"?>
<TU  xmlns="http://example.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://example.com tu.xsd">
  <employee>
    <post>Manager</post>
    <salary>40000</salary>
    <gender>male</gender>
    <username>userA</username>
    <password>Axyz1234</password>
  </employee>
  <employee>
    <post>Supervisor</post>
    <salary>30000</salary>
    <gender>female</gender>
    <username>userB</username>
    <password>Babc1234</password>
  </employee>
</TU>
